spring:
  datasource:
    url: jdbc:h2:mem:quizapp
    driverClassName: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true